// lib/mock-data/accommodations.ts
import { Accommodation } from '@/types/accommodation';

export const mockAccommodations: Accommodation[] = [
  {
    id: "zuma-rock-resort-1",
    type: 'resort',
    propertyName: "Zuma Rock Resort",
    location: "Daura, Niger state",
    images: ["/images/pool-image.png", "/images/deal-zuma-1.png", "/images/deal-zuma-2.png"],
    host: { name: "Zuma Rock Resort", title: "Hospitality Hero", avatar: "/images/placeholder-logo.svg", isVerified: true },
    rating: 4.8,
    reviews: 147,
    features: [
      { text: "Reservation available" },
      { text: "Fully Refundable" },
      { text: "Accessibility options" },
      { text: "Suitable for Businesses" },
    ],
    discount: 30,
    originalPrice: 150000,
    currentPrice: 105000.00,
    priceType: "Deal",
    description: "Experience luxury and comfort at the foot of the iconic Zuma Rock. Our resort offers world-class amenities and breathtaking views.",
    amenities: ["Pool", "Restaurant", "Gym", "Spa", "Conference Hall", "Free Wi-Fi"],
  },
  {
    id: "lekki-bungalow-2",
    type: 'bungalow',
    propertyName: "4 Bedroom Bungalow",
    location: "Lekki Phase 1, Lagos state",
    images: ["/images/deal-zuma-3.png", "/images/deal-zuma-4.png", "/images/pool-image.png"],
    host: { name: "Lolade Properties", title: "Hospitality Hero", avatar: "/images/placeholder-user.jpg", isVerified: true },
    rating: 4.5,
    reviews: 89,
    features: [
      { text: "No Reservation" },
      { text: "Refundable caution deposit" },
      { text: "Accessibility options" },
      { text: "Family-friendly" },
    ],
    discount: undefined,
    originalPrice: undefined,
    currentPrice: 120000.00,
    priceType: "Premium",
    description: "A spacious and modern 4-bedroom bungalow located in the heart of Lekki Phase 1. Perfect for families or groups seeking comfort and convenience.",
    amenities: ["Air Conditioning", "Kitchen", "Parking", "Security", "Garden", "Washing Machine"],
  },
  {
    id: "ph-apartment-3",
    type: 'apartment',
    propertyName: "Riverside Luxury Apartment",
    location: "GRA Phase 2, Port Harcourt",
    images: ["/images/accom-apartments.png", "/images/pool-image.png"],
    host: { name: "PH Rentals", title: "Property Manager", avatar: "/images/placeholder-logo.svg", isVerified: false },
    rating: 4.2,
    reviews: 55,
    features: [
      { text: "Reservation available" },
      { text: "Non-refundable" },
      { text: "City View" },
    ],
    discount: 10,
    originalPrice: 80000,
    currentPrice: 72000.00,
    priceType: "Regular",
    description: "Modern and stylish apartment offering stunning views of the city. Comes with essential amenities for a comfortable stay.",
    amenities: ["Air Conditioning", "Kitchenette", "Balcony", "Free Wi-Fi", "Elevator"],
  },
  {
    id: "abuja-villa-4",
    type: 'villa',
    propertyName: "Asokoro Presidential Villa",
    location: "Asokoro, Abuja",
    images: ["/images/accom-mansions.png", "/images/pool-image.png"], // Using mansion image as placeholder
    host: { name: "Prestige Homes", title: "Luxury Host", avatar: "/images/placeholder-user.jpg", isVerified: true },
    rating: 5.0,
    reviews: 25,
    features: [
      { text: "Private Pool" },
      { text: "Fully Serviced" },
      { text: "High Security" },
      { text: "Suitable for VIPs" },
    ],
    discount: undefined,
    originalPrice: undefined,
    currentPrice: 550000.00,
    priceType: "Premium",
    description: "Experience unparalleled luxury in this exclusive villa located in the prestigious Asokoro district. Features a private pool, chef services, and top-tier security.",
    amenities: ["Private Pool", "Chef Service", "Gym", "Cinema Room", "Parking", "Security", "Garden"],
  },
   {
    id: "uyo-duplex-5",
    type: 'duplex',
    propertyName: "Ekaette's Cozy Duplex",
    location: "Ewet Housing Estate, Uyo",
    images: ["/images/accom-duplexes.png", "/images/pool-image.png"],
    host: { name: "Ekaette Bassey", title: "Home Owner", avatar: "/images/placeholder-user.jpg", isVerified: false },
    rating: 4.0,
    reviews: 30,
    features: [
      { text: "Self Catering" },
      { text: "Quiet Neighborhood" },
      { text: "Family-friendly" },
    ],
    discount: 5,
    originalPrice: 60000,
    currentPrice: 57000.00,
    priceType: "Regular",
    description: "A comfortable and well-maintained duplex in a serene residential estate. Ideal for families looking for a home away from home.",
    amenities: ["Air Conditioning", "Kitchen", "Parking", "Garden", "Living Room"],
  },
   {
    id: "lagos-apartment-6",
    type: 'apartment',
    propertyName: "Ikoyi Serviced Apartment",
    location: "Ikoyi, Lagos state",
    images: ["/images/accom-apartments.png", "/images/deal-zuma-1.png"],
    host: { name: "Lagos Luxury Stays", title: "Hospitality Hero", avatar: "/images/placeholder-logo.svg", isVerified: true },
    rating: 4.7,
    reviews: 112,
    features: [
      { text: "Daily Housekeeping" },
      { text: "Gym Access" },
      { text: "24/7 Power" },
    ],
    discount: undefined,
    originalPrice: undefined,
    currentPrice: 180000.00,
    priceType: "Premium",
    description: "Premium serviced apartment in the exclusive Ikoyi neighborhood. Enjoy top-notch amenities and services.",
    amenities: ["Pool", "Gym", "Air Conditioning", "Kitchen", "Free Wi-Fi", "Parking", "Security"],
  },
  {
    id: "niger-resort-7",
    type: 'resort',
    propertyName: "Gurara Waterfalls Resort",
    location: "Gurara, Niger state",
    images: ["/images/deal-zuma-2.png", "/images/pool-image.png"],
    host: { name: "Nature Resorts Ltd", title: "Eco Host", avatar: "/images/placeholder-logo.svg", isVerified: false },
    rating: 4.3,
    reviews: 68,
    features: [
      { text: "Nature View" },
      { text: "Restaurant On-site" },
      { text: "Guided Tours Available" },
    ],
    discount: 15,
    originalPrice: 90000,
    currentPrice: 76500.00,
    priceType: "Deal",
    description: "Escape to nature at this serene resort near the beautiful Gurara Waterfalls. Perfect for relaxation and adventure.",
    amenities: ["Restaurant", "Bar", "Parking", "Tour Desk", "Garden"],
  },
];
